### ISSUE TITLE
Image set did not change across days

### ISSUE THREAD

**Issue by elvandy** [jefferythewind/appetite_tamer#13]
@jefferythewind The image set did not change across days. Can you please check the code for this part? This issue probably needs to be fixed first. Thank you!

**Comment by jefferythewind** [comment]
@elvandy Sure thing, I have noticed the same thing.

**Comment by jefferythewind** [comment]
@elvandy I am looking into the issue a little more.  It looks like there has been an issue with the image files and the app is unable to get them.  I am looking into a way to recover the files but just have to ask you, do you have a backup of all the image files that you made for this app?

**Comment by jefferythewind** [comment]
@elvandy after looking more into the issue.  All those image files had been stored on Parse's file server and were NOT migrated with the database.  The database had migrated fine, but the image files were still being served by parse.com.  

It was really my fault that this was overlooked.  Everything was working since the files were still there until early this month.  Since parse.com has shut down, the app cannot find those files anymore.  I think there is 1 set of images stored locally in the app that it uses as default.  That is why we see the same set everyday.

I hope you still have a complete set of the images.  If not maybe they have a complete set of the images at the dali lab?

**Comment by jefferythewind** [comment]
After updating the database with the image sets, the images are changes across days for me, marking as done.
